/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Keep empty registration ranges available on Mach-O. The Apple linker
 * synthesizes section start and end symbols for these sections.
 */

#ifdef __APPLE__
__asm__(
	".section __ZINIT,__i0\n"
	".section __ZINIT,__i1\n"
	".section __ZINIT,__i2\n"
	".section __ZINIT,__i3\n"
	".section __ZINIT,__i4\n"
	".section __ZINIT,__i5\n"
	".section __ZINITARR,__array\n"
	".section __ZNATIVE,__n0\n"
	".section __ZNATIVE,__n1\n"
	".section __ZNATIVE,__n2\n"
	".section __ZNATIVE,__n3\n"
	".section __ZNATIVE,__n4\n"
	".section __ZNSITASK,__s0\n"
	".section __ZNSITASK,__s1\n"
	".section __ZNSITASK,__s2\n"
	".section __ZNSITASK,__s3\n"
	".section __ZNSITASK,__s4\n"
	".section __ZNSITASK,__s5\n"
	".section __ZNSITASK,__s6\n"
	".section __ZITER,__device\n"
	".section __ZITER,__static_threads\n"
	".section __ZITER,__k_timer\n"
	".section __ZITER,__k_mem_slab\n"
	".section __ZITER,__k_heap\n"
	".section __ZITER,__k_mutex\n"
	".section __ZITER,__k_stack\n"
	".section __ZITER,__k_msgq\n"
	".section __ZITER,__k_mbox\n"
	".section __ZITER,__k_pipe\n"
	".section __ZITER,__k_sem\n"
	".section __ZITER,__k_event\n"
	".section __ZITER,__k_queue\n"
	".section __ZITER,__k_fifo\n"
	".section __ZITER,__k_lifo\n"
	".section __ZITER,__k_condvar\n"
	".section __ZITER,__log_const\n"
	".section __ZITER,__log_dynamic\n"
	".section __ZITER,__log_msg_ptr\n"
	".section __ZITER,__log_mpsc_pbuf\n"
	".section __ZITER,__log_backend\n"
	".section __ZITER,__log_link\n"
	".section __ZITER,__shell\n"
	".section __ZITER,__shell_root\n"
	".section __ZITER,__shell_subcmd\n"
	".section __ZITER,__shell_dynamic\n"
	".section __ZITER,__rtio\n"
	".section __ZITER,__rtio_pool\n"
	".section __ZITER,__rtio_iodev\n"
	".section __ZITER,__rtio_sqe_pool\n"
	".section __ZITER,__rtio_cqe_pool\n"
	".section __ZITER,__zbus_channel\n"
	".section __ZITER,__zbus_chan_obs\n"
	".section __ZITER,__zbus_obs_mask\n"
	".section __ZITER,__zbus_observer\n"
	".section __ZITER,__zbus_shadow\n"
	".section __ZITER,__api_entropy\n"
	".section __ZITER,__api_uart\n"
);
#endif
